-- AI provider configuration stored in the database so admins can manage keys from the admin panel.
create table if not exists public.ai_providers (
  id bigint generated by default as identity primary key,
  vendor text not null unique,
  api_key text not null,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.ai_providers enable row level security;

create policy "Admins can manage AI providers"
  on public.ai_providers
  for all
  using (true)
  with check (true);

insert into public.ai_providers (vendor, api_key, active)
values
  ('openai', '', true),
  ('google', '', true)
on conflict (vendor) do nothing;
